#!/usr/bin/env python3
"""Import only this repository's local Codex sessions into the knowledge base."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CODEX_HOME = Path.home() / ".codex"
ARCHIVE_DIR = CODEX_HOME / "archived_sessions"
SESSIONS_DIR = CODEX_HOME / "sessions"
OUT_DIR = ROOT / "docs" / "knowledge" / "codex_sessions"
INDEX_PATH = ROOT / "docs" / "knowledge" / "CHAT_INDEX.md"
SESSION_INDEX_PATH = CODEX_HOME / "session_index.jsonl"
SECRET_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9_-]{16,}"),
    re.compile(r"(?i)(OPENAI_API_KEY|ANTHROPIC_API_KEY|GEMINI_API_KEY|DEEPSEEK_API_KEY)\s*=\s*\S+"),
]


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    except FileNotFoundError:
        return []
    return rows


def content_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for item in content:
        if isinstance(item, str):
            parts.append(item)
            continue
        if not isinstance(item, dict):
            continue
        text = item.get("text")
        if isinstance(text, str):
            parts.append(text)
    return "\n".join(part for part in parts if part).strip()


def extract_session(path: Path) -> dict[str, Any] | None:
    rows = read_jsonl(path)
    if not rows:
        return None

    meta: dict[str, Any] = {}
    messages: list[dict[str, str]] = []
    for row in rows:
        payload = row.get("payload", {})
        if row.get("type") == "session_meta" and isinstance(payload, dict):
            meta = payload
            continue
        if row.get("type") != "response_item" or not isinstance(payload, dict):
            continue
        if payload.get("type") != "message":
            continue
        role = payload.get("role")
        if role not in {"user", "assistant"}:
            continue
        text = content_text(payload.get("content"))
        if not text:
            continue
        messages.append({"role": role, "text": text})

    cwd = str(meta.get("cwd", ""))
    if not cwd or Path(cwd).resolve() != ROOT.resolve():
        return None

    session_id = str(meta.get("id") or path.stem)
    title = load_session_titles().get(session_id, session_id)
    first_user = next(
        (
            m["text"].splitlines()[0]
            for m in messages
            if m["role"] == "user" and not m["text"].lstrip().startswith("<environment_context>")
        ),
        "",
    )
    if first_user:
        title = first_user[:80]

    return {
        "id": session_id,
        "path": path,
        "source_size": path.stat().st_size,
        "timestamp": meta.get("timestamp", ""),
        "cwd": cwd,
        "title": title,
        "messages": messages,
    }


def slug(value: str) -> str:
    cleaned = []
    for char in value.lower():
        if char.isalnum():
            cleaned.append(char)
        elif char in {" ", "-", "_"}:
            cleaned.append("-")
    result = "".join(cleaned).strip("-")
    while "--" in result:
        result = result.replace("--", "-")
    return result[:60] or "session"


def load_session_titles() -> dict[str, str]:
    titles: dict[str, str] = {}
    for row in read_jsonl(SESSION_INDEX_PATH):
        session_id = row.get("id")
        thread_name = row.get("thread_name")
        if isinstance(session_id, str) and isinstance(thread_name, str) and thread_name:
            titles[session_id] = thread_name
    return titles


def write_session(session: dict[str, Any]) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = str(session.get("timestamp") or "")
    stamp = timestamp.replace(":", "").replace("-", "").replace(".", "")
    stamp = stamp[:15] if stamp else "unknown-date"
    filename = f"{stamp}-{slug(session['title'])}-{session['id'][:13]}.md"
    out_path = OUT_DIR / filename

    lines = [
        f"# Codex Session: {session['title']}",
        "",
        "<!-- Generated by scripts/import_codex_sessions.py. Do not edit by hand. -->",
        "",
        f"- Session ID: `{session['id']}`",
        f"- Timestamp: `{session.get('timestamp', '')}`",
        f"- Source: `{session['path']}`",
        f"- CWD: `{session.get('cwd', '')}`",
        "",
        "## Transcript",
        "",
    ]
    for message in session["messages"]:
        speaker = "User" if message["role"] == "user" else "Assistant"
        lines.extend([f"### {speaker}", "", sanitize_text(message["text"]).strip(), ""])

    out_path.write_text(clean_markdown("\n".join(lines)) + "\n", encoding="utf-8")
    return out_path


def sanitize_text(text: str) -> str:
    sanitized = text
    for pattern in SECRET_PATTERNS:
        sanitized = pattern.sub("[redacted-secret]", sanitized)
    return sanitized


def clean_markdown(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip()


def main() -> int:
    sessions_by_id: dict[str, dict[str, Any]] = {}
    paths = list(SESSIONS_DIR.glob("**/*.jsonl")) + list(ARCHIVE_DIR.glob("*.jsonl"))
    for path in sorted(paths):
        session = extract_session(path)
        if session:
            current = sessions_by_id.get(session["id"])
            if current is None or _is_better_session(session, current):
                sessions_by_id[session["id"]] = session

    sessions = sorted(sessions_by_id.values(), key=lambda item: str(item.get("timestamp") or ""))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob("*.md"):
        old.unlink()

    written = []
    for session in sessions:
        written.append((session, write_session(session)))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Chat Index",
        "",
        f"Last imported: `{now}`",
        "",
        f"Scope: only Codex sessions with `cwd == {ROOT}`",
        "",
        f"Imported project sessions: {len(written)}",
        "",
        "## Sessions",
        "",
    ]
    if not written:
        lines.append("No matching Codex project sessions found.")
    for session, path in written:
        rel = path.relative_to(ROOT)
        lines.append(f"- [{session['title']}](./{rel.relative_to(Path('docs/knowledge'))}) - `{session.get('timestamp', '')}`")

    INDEX_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Imported {len(written)} sessions into {OUT_DIR}")
    return 0


def _is_better_session(candidate: dict[str, Any], current: dict[str, Any]) -> bool:
    """Prefer the most complete copy when the same session exists in active and archive dirs."""
    candidate_messages = len(candidate.get("messages", []))
    current_messages = len(current.get("messages", []))
    if candidate_messages != current_messages:
        return candidate_messages > current_messages

    candidate_size = int(candidate.get("source_size") or 0)
    current_size = int(current.get("source_size") or 0)
    if candidate_size != current_size:
        return candidate_size > current_size

    return str(candidate.get("timestamp") or "") > str(current.get("timestamp") or "")


if __name__ == "__main__":
    raise SystemExit(main())
